/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/
#include <unit/simple_pub/unit_base.h>

class simple_pub : public unit::simple_pub::Base {
public:
  simple_pub(const Args& args, const std::optional<std::string_view>& name_override = {}) 
  : unit::simple_pub::Base(name_override)
  {}


  virtual unit::simple_pub::PublishAt1Hz::Output
  PublishAt1Hz(const unit::simple_pub::PublishAt1Hz::Input &input) override;

};