/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/

#include <simple_sub.h>

using namespace unit::simple_sub;


OnChatter::Output simple_sub::OnChatter(const OnChatter::Input& input) {
    static_assert(false, "Implement me");
}
